name: taskati
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  lottie: ^3.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/

  fonts:
  - family: Poppins
    fonts:
    - asset: assets/fonts/Poppins-Regular.tff
      weight: 400
    - asset: assets/fonts/Poppins-Medium.tff
      weight: 500
    - asset: assets/fonts/Poppins-SemiBold.tff
      weight: 600
    - asset: assets/fonts/Poppins-Bold.tff
      weight: 700
    - asset: assets/fonts/Poppins-Black.tff
      weight: 900
    